const q=s=>document.querySelector(s),entry=q('#entry'),inbox=q('#inbox'),form=q('#form'),input=q('#cdk'),error=q('#error'),messages=q('#messages'),toast=q('#toast');let activeCdk='',activeAddress='',timer=null,copyTimer=null,lastFingerprint=null,loading=false;
const getCdk=()=>{const m=location.pathname.match(/^\/c\/([^/]+)$/);return m?decodeURIComponent(m[1]).toUpperCase():''};
async function api(path){const r=await fetch(path,{headers:{Accept:'application/json'},cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||'请求失败');return d}
function notify(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)}
const fullTime=v=>v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'未知时间',shortTime=v=>v?new Date(v).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false}):'—';
function remain(target){const s=Math.max(0,Math.floor((new Date(target)-Date.now())/1000)),d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60),x=s%60;return d?`${d}天 ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`:`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`}
function renderLife(box){clearInterval(timer);const target=box.deactivate_due_at||box.cdk_expires_at||box.purge_due_at;if(!target){q('#lifecycle').classList.add('hidden');return}q('#lifecycle').classList.remove('hidden');q('#life-title').textContent=box.deactivate_due_at?'隐藏邮箱自动停用':box.cdk_expires_at?'CDK 自动失效':'邮件自动清理';q('#life-copy').textContent='服务器将按邮箱策略自动执行';const update=()=>q('#countdown').textContent=remain(target);update();timer=setInterval(update,1000)}
function row(item,index){const b=document.createElement('button');b.className='message mail-card card';b.type='button';b.dataset.messageId=item.id||'';b.dataset.sender=item.sender||'';b.dataset.receivedAt=item.received_at||'';b.dataset.timestamp=item.received_at||'';b.dataset.otp=item.otp_code||'';b.dataset.recipient=activeAddress;b.innerHTML='<span class="recipient to" hidden></span><span class="message-head"><span class="message-sender sender from"></span><time class="time received-at"></time></span><span class="message-subject subject"></span><span class="message-preview preview body"></span>';b.querySelector('.recipient').textContent=activeAddress;b.querySelector('.message-sender').textContent=item.sender||'未知发件人';const time=b.querySelector('time');time.textContent=shortTime(item.received_at);time.dateTime=item.received_at||'';b.querySelector('.message-subject').textContent=item.subject||'无主题';b.querySelector('.message-preview').textContent=item.preview||'没有可显示的文本内容';b.onclick=()=>openMail(item.id,b);if(index===0)b.dataset.first='1';return b}
async function load(cdk,silent=false,forceSync=false){if(loading)return;loading=true;if(!silent)error.textContent='';try{const d=await api(`/api/public/c/${encodeURIComponent(cdk)}?limit=20${forceSync?'&refresh=1':''}`);activeCdk=cdk;activeAddress=d.mailbox.address||'';entry.classList.add('hidden');inbox.classList.remove('hidden');q('#address').textContent=activeAddress;q('#summary-meta').textContent=`${d.mailbox.service_name||'未命名邮箱'} · CDK 安全访问 · 最近更新于刚刚`;q('#count').textContent=`${d.mailbox.message_count} 封邮件`;const fingerprint=d.items.map(x=>`${x.id}:${x.received_at}:${x.otp_code||''}`).join('|');if(fingerprint!==lastFingerprint){lastFingerprint=fingerprint;messages.replaceChildren();if(!d.items.length){const n=document.createElement('div');n.className='none';n.textContent='暂时没有收到邮件';messages.append(n);q('#detail').classList.add('hidden');q('#empty').classList.remove('hidden')}else{d.items.forEach((x,i)=>messages.append(row(x,i)));messages.querySelector('[data-first]')?.click()}}renderLife(d.mailbox)}catch(e){if(!silent){entry.classList.remove('hidden');inbox.classList.add('hidden');error.textContent=e.message}}finally{loading=false}}
async function openMail(id,button){document.querySelectorAll('.message').forEach(x=>x.classList.toggle('active',x===button));try{const d=await api(`/api/public/c/${encodeURIComponent(activeCdk)}/messages/${id}`),x=d.item;q('#empty').classList.add('hidden');q('#detail').classList.remove('hidden');q('#subject').textContent=x.subject||'无主题';q('#meta').textContent=`${x.sender||'未知发件人'} · ${fullTime(x.received_at)}`;q('#body').textContent=x.body_text||x.preview||'没有可显示的文本内容';const otp=/^(?:\d{4}|\d{6})$/.test(x.otp_code||'')?x.otp_code:'';q('#otp-box').classList.toggle('hidden',!otp);q('#otp').textContent=otp;q('#otp-label').textContent=otp?`${otp.length} 位数字验证码`:'';q('#copy span').textContent='复制验证码';q('#copy-status').textContent=''}catch(e){notify(e.message)}}
form.onsubmit=e=>{e.preventDefault();const c=input.value.trim().toUpperCase();if(c.length<8){error.textContent='请输入完整 CDK';return}lastFingerprint=null;history.pushState({},'',`/c/${encodeURIComponent(c)}`);load(c)};
q('#refresh').onclick=async()=>{if(!activeCdk)return;const button=q('#refresh'),label=button.textContent;button.disabled=true;button.textContent='查询中…';await load(activeCdk,true,true);button.textContent='已查询';setTimeout(()=>{button.disabled=false;button.textContent=label},900)};
q('#copy').onclick=async()=>{const code=q('#otp').textContent;if(!code)return;try{await navigator.clipboard.writeText(code)}catch{const area=document.createElement('textarea');area.value=code;document.body.append(area);area.select();document.execCommand('copy');area.remove()}clearTimeout(copyTimer);q('#copy span').textContent='已复制';q('#copy-status').textContent=`验证码 ${code} 已复制到剪贴板`;copyTimer=setTimeout(()=>{q('#copy span').textContent='复制验证码';q('#copy-status').textContent=''},1800)};
const initial=getCdk();if(initial){input.value=initial;load(initial)}setInterval(()=>{if(activeCdk)load(activeCdk,true)},2000);
